version: '3.7'

services:

  customers:
    build:
      context: ./services/customer
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABSE_URL=postgres://postgres:postgres@customers-db:5432/customers_dev    # nuevo
      - DATABASE_TEST_URL=postgres:postgres@customers-db:5432/customers_test  # nuevo
    depends_on:  # nuevo
      - customers-db

  customers-db:  # nuevo
    build:
      context: ./services/customer/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

