version: '3.7'
 
services:
 
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABSE_URL=postgres://postgres:postgres@customers-db:5432/users_dev    # nuevo
      - DATABASE_TEST_URL=postgres:postgres@customers-db:5432/users_test  # nuevo
    depends_on:  # nuevo
      - customers-db
  
  customers-db:  # nuevo
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    enviroment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
